version: '3'
networks:
  app-network:
    driver: bridge
services:
  nginx:
    image: 'nginx:stable-alpine'
    container_name: c-nginx
    ports:
      - 8989:3000
      - 443:443
    volumes:
      - './src:/var/www/html'
      - './nginx-default.conf:/etc/nginx/conf.d/default.conf'
    networks:
      - app-network
